Vagrant::configure("2") do |config|

    # Use a standard box
    config.vm.box = 'centos64'
    config.vm.box_url = 'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box'

    # Define our virtual machine settings
    config.vm.define :centos64 do |centos64|

        centos64.vm.hostname = "sqtestvm1.localdomain"
        centos64.vm.network :private_network, ip: "192.168.33.50"
        centos64.vm.network :forwarded_port, guest: 80, host: 9001
        centos64.vm.synced_folder ".", "/usr/share/shard-query", :nfs => false

        # Here we customize our virtualbox provider. If there are others, add them accordingly below
        centos64.vm.provider :virtualbox do |vbox|
            vbox.gui = false

            vbox.customize [ 'modifyvm', :id, '--cpus', '8' ]
            vbox.customize [ 'modifyvm', :id, '--memory', '4096' ]
        end

        config.vm.provision :shell, :path => "provision.sh"

    end
end
