<?php return array (
  'util.php' => '/usr/share/shard-query/ui/protected/class/util.php',
  'DBRESTController.php' => '/usr/share/shard-query/ui/protected/class/DBRESTController.php',
  'Process.php' => '/usr/share/shard-query/ui/protected/class/Process.php',
  'response.php' => '/usr/share/shard-query/ui/protected/class/response.php',
  'GearmanFunctionNames.php' => '/usr/share/shard-query/ui/protected/model/GearmanFunctionNames.php',
  'GearmanWorkers.php' => '/usr/share/shard-query/ui/protected/model/GearmanWorkers.php',
  'Schemata.php' => '/usr/share/shard-query/ui/protected/model/Schemata.php',
  'SchemataConfigItems.php' => '/usr/share/shard-query/ui/protected/model/SchemataConfigItems.php',
  'SchemataConfig.php' => '/usr/share/shard-query/ui/protected/model/SchemataConfig.php',
  'ShardRangeMap.php' => '/usr/share/shard-query/ui/protected/model/ShardRangeMap.php',
  'Jobs.php' => '/usr/share/shard-query/ui/protected/model/Jobs.php',
  'ShardMap.php' => '/usr/share/shard-query/ui/protected/model/ShardMap.php',
  'Shards.php' => '/usr/share/shard-query/ui/protected/model/Shards.php',
  'GearmanFunctions.php' => '/usr/share/shard-query/ui/protected/model/GearmanFunctions.php',
  'JobWorkerStatus.php' => '/usr/share/shard-query/ui/protected/model/JobWorkerStatus.php',
  'ColumnSequences.php' => '/usr/share/shard-query/ui/protected/model/ColumnSequences.php',
  'ShardColumns.php' => '/usr/share/shard-query/ui/protected/model/ShardColumns.php',
  'GearmanJobServers.php' => '/usr/share/shard-query/ui/protected/model/GearmanJobServers.php',
);