create table empsalary(depname varchar(20), empno numeric(10),salary numeric(10));
insert into empsalary values ( 'develop'   ,    11 ,   5200 );
insert into empsalary values ( 'develop'   ,     7 ,   4200 );
insert into empsalary values ( 'develop'   ,     9 ,   4500 );
insert into empsalary values ( 'develop'   ,     8 ,   6000 );
insert into empsalary values ( 'develop'   ,    10 ,   5200 );
insert into empsalary values ( 'personnel' ,     5 ,   3500 );
insert into empsalary values ( 'personnel' ,     2 ,   3900 );
insert into empsalary values ( 'sales'     ,     3 ,   4800 );
insert into empsalary values ( 'sales'     ,     1 ,   5000 );
insert into empsalary values ( 'sales'     ,     4 ,   4800 );
